# Generated by Django 4.0.3 on 2022-07-13 02:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('dob', models.DateField()),
                ('aadhar_number', models.BigIntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('account_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
