# Generated by Django 4.0.3 on 2022-07-13 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_accountuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='password',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='aadhar_number',
            field=models.BigIntegerField(blank=True, default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_type',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='balance',
            field=models.IntegerField(blank=True, default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='dob',
            field=models.DateField(blank=True, default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='gender',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='DEFAULT VALUE', max_length=128, region=None),
        ),
    ]
