# Generated by Django 4.0.3 on 2022-07-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='transaction',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
