# Generated by Django 4.0.3 on 2022-08-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_records_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
